import pandas as pd 
df = pd.read_csv("D:\\wps\\xuexi\\flight.csv")
print("数据条数:",df.shape)
print("各字段类型")
print(df.dtypes)
print("数据头部")
print(df.head())
print("数据尾部")
print(df.tail())
print("数据字段:",df.columns.tolist())
print("数据概括:")
print(df.info)
df = df.fillna(0)
print("填充缺失值后的数据概况：")
print(df.info())