import numpy as np
n1 = np.arange(12).reshape(3,4)
sum = np.sum(n1,axis=0)
min = np.min(n1,axis=1)
print("每一列的和为",sum)
print("每一行最小值为",min)
n2 = np.array([2,5,6])
sqrt2 = np.sqrt(n2)
mean = np.mean(n2)
std = np.std(n2)
eachstd = (n2-mean)/std
print("数组n2:",n2)
print("每个元素的平方根为：",sqrt2)
print("每个元素标准差为：",eachstd)
n3 = np.arange(9)
sqrt3 = np.square(n3)
elems = n3[2]
elem2 = n3[2:5]
print("n3:",n3)
print("每个元素平方为",sqrt3)
print("位置2的元素为：",elems)
print("2-5的元素为：",elem2)
n4 = np.random.randint(0,10,(3,3))
n5 = np.random.randint(0,10,(3,3))
n6 = np.vstack((n4,n5))
n7 = np.hstack((n4,n5))
print("n4为：")
print(n4)
print("n5为：")
print(n5)
print("垂直合并n6为：")
print(n6)
print("水平合并n7为：")
print(n7)